"""
Django settings for issc project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env for development. We explicitly allow
# the .env values to override existing environment variables when running
# locally so a mistakenly-set system environment (e.g. a placeholder
# like 'your-email@example.com') doesn't cause confusion. This is intended
# for development only; in production you should rely on secure environment
# variables and avoid committing secrets to .env.
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# Add these settings to fix "Session data corrupted" messages
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["issc.study", "www.issc.study", "72.62.66.193", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main"
]

AUTH_USER_MODEL = 'main.AccountRegistration'
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]
LOGIN_URL = '/login/'  # Redirect unauthenticated users to login



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "issc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.incident_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "issc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# MySQL configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME", 'issc'),
        'USER': os.getenv("DB_USER", 'root'),
        'PASSWORD': os.getenv("DB_PASSWORD", ''),
        'HOST': os.getenv("DB_HOST", '127.0.0.1'),
        'PORT': os.getenv("DB_PORT", '3306'),
    }
}

# SQLite config (for development fallback)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



RECORDING_URL = '/recordings/'
RECORDING_ROOT = BASE_DIR / 'recordings'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# NOTE: The project previously allowed overriding these via environment variables.
# For immediate testing with the SMTP credentials you provided, we set the
# Gmail account and its App Password here. In production you should instead
# set environment variables and NOT commit secrets in code.

# Gmail account used for sending notifications
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') or 'vinceerickquiozon14@gmail.com'

# Gmail App Password (16 characters). Remove spaces if you copied it grouped.
# The app password you provided was "viqb pwkq lhle rgez" — the actual
# credential used by SMTP should have no spaces: "viqbpwklhle rgez" -> fix below.
# Set EMAIL_HOST_PASSWORD via env var in production instead of editing this file.
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') or 'viqbpwklhlergez'

# Default from email for outgoing messages
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# PhilSMS Configuration
PHILSMS_API_BASE = os.getenv('PHILSMS_API_BASE', 'https://dashboard.philsms.com/api/v3')
PHILSMS_API_TOKEN = os.getenv('PHILSMS_API_TOKEN', '377|DT0C9GeHCgLXdNt5oxjajd3QqdLlKcqMHv5KLZcE3b45ab96')
PHILSMS_SENDER_ID = os.getenv('PHILSMS_SENDER_ID', 'PhilSMS')
PHILSMS_RECIPIENT = os.getenv('PHILSMS_RECIPIENT', '09945349194')
PHILSMS_COOLDOWN_SECONDS = int(os.getenv('PHILSMS_COOLDOWN_SECONDS', '900'))

# PhilSMS configuration (can be overridden via environment variables)
PHILSMS_API_BASE = os.getenv('PHILSMS_API_BASE', 'https://dashboard.philsms.com/api/v3')
# Put your PhilSMS API token in the environment or override here
PHILSMS_API_TOKEN = os.getenv('PHILSMS_API_TOKEN', '377|DT0C9GeHCgLXdNt5oxjajd3QqdLlKcqMHv5KLZcE3b45ab96')
# Approved sender id (alphanumeric or phone number). Set this to the sender approved in your dashboard
PHILSMS_SENDER_ID = os.getenv('PHILSMS_SENDER_ID', 'PhilSMS')
# Default recipient for unauthorized alerts (local format allowed)
PHILSMS_RECIPIENT = os.getenv('PHILSMS_RECIPIENT', '09945349194')
# Cooldown in seconds between SMS alert sends (default 15 minutes)
PHILSMS_COOLDOWN_SECONDS = int(os.getenv('PHILSMS_COOLDOWN_SECONDS', str(15 * 60)))
