#!/bin/bash

# Automatic Backup Scheduler for Linux (Ubuntu 24.04)
# This script creates a cron job that runs daily at 00:00 (midnight) Asia/Manila time
#
# USAGE:
#   chmod +x setup_backup_scheduler_linux.sh
#   sudo ./setup_backup_scheduler_linux.sh

echo "==============================================="
echo "ISSC Automatic Backup Scheduler Setup (Linux)"
echo "==============================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "ERROR: This script must be run as root or with sudo"
    echo "Please run: sudo ./setup_backup_scheduler_linux.sh"
    exit 1
fi

# Get the actual user who ran sudo
ACTUAL_USER=${SUDO_USER:-$USER}
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Determine the correct python and manage.py paths
if [ -f "$SCRIPT_DIR/venv/bin/python" ]; then
    PYTHON_PATH="$SCRIPT_DIR/venv/bin/python"
elif [ -f "/var/www/issc/venv/bin/python" ]; then
    PYTHON_PATH="/var/www/issc/venv/bin/python"
else
    PYTHON_PATH="$(which python3)"
fi

if [ -f "$SCRIPT_DIR/issc/manage.py" ]; then
    MANAGE_PATH="$SCRIPT_DIR/issc/manage.py"
    WORKING_DIR="$SCRIPT_DIR/issc"
elif [ -f "/var/www/issc/issc/manage.py" ]; then
    MANAGE_PATH="/var/www/issc/issc/manage.py"
    WORKING_DIR="/var/www/issc/issc"
else
    echo "ERROR: Could not find manage.py"
    exit 1
fi

echo "Found Python: $PYTHON_PATH"
echo "Found manage.py: $MANAGE_PATH"
echo "Working directory: $WORKING_DIR"
echo ""

# Create the backup script
BACKUP_SCRIPT="/usr/local/bin/issc_auto_backup.sh"
echo "Creating backup script at: $BACKUP_SCRIPT"

cat > $BACKUP_SCRIPT << EOF
#!/bin/bash
# ISSC Automatic Backup Script
# Generated by setup_backup_scheduler_linux.sh

# Change to project directory
cd "$WORKING_DIR"

# Run the backup command
$PYTHON_PATH "$MANAGE_PATH" auto_backup --cleanup --keep-days 30 >> /var/log/issc_backup.log 2>&1

# Log completion
echo "Backup completed at \$(date)" >> /var/log/issc_backup.log
EOF

# Make the script executable
chmod +x $BACKUP_SCRIPT
echo "✓ Backup script created and made executable"

# Create log file with proper permissions
touch /var/log/issc_backup.log
chmod 644 /var/log/issc_backup.log
echo "✓ Log file created: /var/log/issc_backup.log"

# Set up cron job
# Convert 00:00 Asia/Manila to UTC for cron
# Manila is UTC+8, so 00:00 Manila = 16:00 UTC (previous day)
# But we'll use the local server time if it's set to Asia/Manila

CRON_JOB="0 0 * * * $BACKUP_SCRIPT"
CRON_USER="$ACTUAL_USER"

# Check if cron job already exists
crontab -u $CRON_USER -l 2>/dev/null | grep -v "issc_auto_backup.sh" | crontab -u $CRON_USER -
(crontab -u $CRON_USER -l 2>/dev/null; echo "$CRON_JOB") | crontab -u $CRON_USER -

echo "✓ Cron job installed for user: $CRON_USER"
echo ""

# Verify timezone
CURRENT_TZ=$(timedatectl | grep "Time zone" | awk '{print $3}')
echo "Current server timezone: $CURRENT_TZ"

if [ "$CURRENT_TZ" != "Asia/Manila" ]; then
    echo ""
    echo "WARNING: Your server timezone is NOT set to Asia/Manila!"
    echo "The backup will run at 00:00 in the current timezone: $CURRENT_TZ"
    echo ""
    echo "To change timezone to Asia/Manila, run:"
    echo "  sudo timedatectl set-timezone Asia/Manila"
    echo ""
fi

echo "==============================================="
echo "✓ Automatic backup scheduler installed!"
echo "==============================================="
echo ""
echo "Task Details:"
echo "  Schedule: Daily at 00:00 (local server time)"
echo "  Script: $BACKUP_SCRIPT"
echo "  Log file: /var/log/issc_backup.log"
echo "  Cleanup: Automatic backups older than 30 days"
echo ""
echo "To verify the cron job, run:"
echo "  crontab -l"
echo ""
echo "To manually run the backup now, run:"
echo "  cd $WORKING_DIR"
echo "  $PYTHON_PATH manage.py auto_backup"
echo ""
echo "To view backup logs:"
echo "  tail -f /var/log/issc_backup.log"
echo ""
echo "To remove the cron job, run:"
echo "  crontab -e"
echo "  (then delete the line containing 'issc_auto_backup.sh')"
echo ""

# Test the backup script
echo "Would you like to test the backup now? (y/n)"
read -r response
if [[ "$response" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Running test backup..."
    sudo -u $CRON_USER $BACKUP_SCRIPT
    echo ""
    echo "Test complete! Check the output above for any errors."
    echo "View the log file: cat /var/log/issc_backup.log"
fi

echo ""
echo "Setup complete!"
