# Generated by Django 5.1.6 on 2025-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('incident', models.TextField()),
                ('request_for_action', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='files/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('sticker_number', models.CharField(max_length=20, unique=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
                ('drivers_license', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('restricted', 'Restricted')], max_length=20)),
                ('qr_code', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Vehicle Registration',
                'verbose_name_plural': 'Vehicle Registrations',
            },
        ),
    ]
