# Generated by Django 5.1.6 on 2025-02-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incidentreport_vehicleregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountregistration',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
