# Generated by Django 5.1.6 on 2025-02-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_facesembeddings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facesembeddings",
            options={
                "verbose_name": "Face Embedding",
                "verbose_name_plural": "Faces Embeddings",
            },
        ),
    ]
