# Generated by Django 5.1.6 on 2025-02-12 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_facesembeddings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentreport",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="vehicleregistration",
            name="date_joined",
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
