# Generated by Django 5.1.6 on 2025-02-13 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_incidentreport_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='time',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
