# Generated by Django 5.1.6 on 2025-02-18 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_incidentreport_date_incidentreport_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='id_number'),
        ),
    ]
