# Generated by Django 5.1.6 on 2025-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_incidentreport_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='last_updated_by',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
