# Generated by Django 5.1.6 on 2025-02-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_incidentreport_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_archived',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
