# Generated by Django 5.1.6 on 2025-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_incidentreport_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='is_archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='last_updated_by',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
