# Generated by Django 5.1.6 on 2025-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_vehicleentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facesembeddings",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="facesembeddings",
            name="image_hash",
        ),
        migrations.AddField(
            model_name="facesembeddings",
            name="front_embedding",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="facesembeddings",
            name="left_embedding",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="facesembeddings",
            name="right_embedding",
            field=models.JSONField(default=dict),
        ),
    ]
