# Generated by Django 5.1.6 on 2025-05-17 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_facesembeddings_embedding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="id_number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Logs",
                "verbose_name_plural": "Face Logs",
            },
        ),
    ]
