# Generated by Django 5.1.6 on 2025-06-12 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_facelogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="facelogs",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
