# Generated by Django 4.2.7 on 2025-11-07 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_facelogs_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedFaceDetection',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=500)),
                ('camera_box_id', models.IntegerField()),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unauthorized Face Detection',
                'verbose_name_plural': 'Unauthorized Face Detections',
                'ordering': ['-detection_timestamp'],
            },
        ),
    ]
