# Generated by Django 4.2.7 on 2025-11-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_unauthorizedfacedetection'),
    ]

    operations = [
    ]
