# Generated by Django 4.2.7 on 2025-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20251107_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='people_involved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
