# Generated by Django 4.2.7 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_incidentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='invalidation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
