# Generated by Django 4.2.7 on 2025-12-09 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_incidentreport_invalidation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='faculty_involved',
            field=models.ManyToManyField(blank=True, related_name='incident_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
